algorand watcher
wormhole-foundation/wormhole-monitor pull request #18
Opened 2022-12-21 13:05 UTC by jumpsiegel

2022-12-21 14:29 UTC, evan-gray requested changes
This is looking pretty good. Can you fill out the `INITIAL_DEPLOYMENT_BLOCK_BY_CHAIN` in consts for Algorand - where the value should be the "fromBlock" to start indexing from as the deployment of the wormhole core contract (to ensure the watcher can backfill every message)

2022-12-21 15:04 UTC, evan-gray reviewed
Couple small things, I think the file name should match the class name so `Algorand.ts` -> `AlgorandWatcher.ts`, and we've been trying to have the commit names prefixed with the folder (like the wormhole repo). Admittedly, would be good to include these in a contributing doc 😛 I'm running it now and will update / approve soon!

2022-12-22 00:17 UTC, evan-gray requested changes
After running this for a while, I started getting the following error:
```
AlgorandWatcher.ts:343
    for (const stxn of b.block.txns) {
                               ^
TypeError: b.block.txns is not iterable
```

2022-12-23 08:01 UTC, heyitaki commented on watcher/src/watchers/AlgorandWatcher.ts
> +export class AlgorandWatcher extends Watcher {
Can we hoist exported consts for visibility?

2022-12-27 14:48 UTC, evan-gray commented on watcher/src/watchers/Algorand.ts
> +// npx pretty-quick
fixed

2022-12-27 14:48 UTC, evan-gray commented on watcher/src/watchers/Algorand.ts
> +      this.appid = 4;
fixed

2022-12-27 14:58 UTC, evan-gray commented on watcher/src/watchers/AlgorandWatcher.ts
> +export class AlgorandWatcher extends Watcher {
fixed

2022-12-27 15:17 UTC, evan-gray commented
testing after rebase and still hitting
```
[2022-12-27 15:16:13.160 +0000] [info] [algorand] fetching info for blocks 23761194 to 23761198
[2022-12-27 15:16:13.309 +0000] [error] [algorand] b.block.txns is not iterable
```

2022-12-27 15:36 UTC, evan-gray commented
Investigating https://algoexplorer.io/block/23761195

2022-12-27 16:59 UTC, evan-gray approved these changes
Seems to be running smoothly after rebase with the empty block fix

2022-12-27 17:00 UTC, merged