Aptos watcher
wormhole-foundation/wormhole-monitor pull request #28
Opened 2022-12-23 20:43 UTC by heyitaki

draft so i can comment as i dev

2022-12-23 21:15 UTC, heyitaki commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
Possible solution might be to slice last 20 blocks (probabilistic assumption that last block was written in that timeframe) and sort before selecting the last one.

2022-12-23 21:15 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +        const blockKey = [block.last_version, timestamp, sequence_number].join('/'); // use custom block key for now so we can include sequence number
Would love to come up with a more generalizable key / storage scheme in a future PR :)

2022-12-23 22:01 UTC, evan-gray requested changes
Only have phone access at the moment, but reviewed the best I could. I just want to confirm (probably worth a comment as well) that this "sequence_number" for the event is shared across emitters. Also see why you wanted to change the "key" stuff. Maybe, we can do that after #27 then rebase this and clean it up. What we will have to consider is that this will show differently than the rest of the watchers in terms of knowing how many blocks went by without messages that we have witnessed. For that, we may consider expanding what the last block info stores (and how).

2022-12-23 22:07 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +import * as dotenv from 'dotenv';
good catch, this is a remnant of some local testing i was doing in that file

2022-12-23 22:52 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +          toBlock = Math.min(fromBlock + getMaximumBatchSize(this.chain) - 1, toBlock); // fix for "block range is too wide" or "maximum batch size is 50, but received 101"
Seems reasonable to me if watch moves there.

2022-12-23 22:53 UTC, evan-gray commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
This reads from a separate file now so I’m not sure this is relevant

2022-12-23 22:53 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +        const blockKey = [block.last_version, timestamp, sequence_number].join('/'); // use custom block key for now so we can include sequence number
👍

2022-12-23 23:08 UTC, heyitaki commented on watcher/src/index.ts
> +// new EVMWatcher('ethereum').watch();
i don't mind either way, I made this change because overall code is reduced even if the entry point is slightly bulkier

I strongly think that we should keep the `watch` method in `Watcher`, but am open to creating a `watch` method wrapper here that utilizes the data struct that mapped chain name to watcher

2022-12-23 23:10 UTC, heyitaki commented on watcher/src/watchers/Watcher.ts
> +  async watch(): Promise<void> {
This allows watchers to re-implement `watch` if need be -- Aptos watcher may potentially do this in the future. Regardless, I feel like it's cleaner and makes sense from an OOP perspective, a `Watcher` should have a `watch` method!

2022-12-23 23:12 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +const APTOS_RPC = 'https://fullnode.mainnet.aptoslabs.com/';
Agreed, since frontend will also likely use this. The motivation was to keep any constants that aren't used by other files local to the only file they're being used in. Doesn't make sense to me to clutter a shared `consts.ts` file if they're only used in one location.

2022-12-23 23:18 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> + * NOTE: The Aptos watcher differs from other watchers in that it uses the event sequence number to
Technically they are different, but in practice they are the same since the sequence number of the event handle = the # of messages sent using that handle which ends up being the same as the WH sequence number

2022-12-23 23:18 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +    if (limit > APTOS_MAX_BATCH_SIZE) {
Fair

2022-12-23 23:20 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +        const vaaKey = makeVaaKey(version, this.chain, emitter, data.sequence);
It's 1:1 and requires 1 less API call (although I guess this call would just be moved to the frontend which is suboptimal). I'll sub in tx hash here

2022-12-23 23:24 UTC, heyitaki commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
@evan-gray what do you mean? This had the latest changes rebased before #27 was merged in

2022-12-24 02:21 UTC, evan-gray commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
How could the blocks have been added out of order, all this object stores is the separate file with key = `chainId`, value = `block/timestamp`

2022-12-24 02:25 UTC, heyitaki commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
`blockInfos[blockInfos.length-1]` is not guaranteed to be the last block that we've processed right? The blocks could (and do) get added out of order as keys to `vaasByBlock`

2022-12-24 02:29 UTC, evan-gray commented
pushed a rebase 🙂

2022-12-24 02:30 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +  async watch(): Promise<void> {
I'm on board!

2022-12-24 02:30 UTC, evan-gray commented on watcher/src/index.ts
> +// new EVMWatcher('ethereum').watch();
Let's try this for now 🙂

2022-12-24 02:32 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +const APTOS_RPC = 'https://fullnode.mainnet.aptoslabs.com/';
In general, yes, but I think that in cases like the RPCs it's nicer for maintenance for them to be in the same place. I realize that this PR moves the max batch size to be spread across files so I guess we'll see how that goes.

2022-12-24 02:35 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +const APTOS_RPC = 'https://fullnode.mainnet.aptoslabs.com/';
Agreed, was thinking about that too... Alternatively, down for a `BATCH_SIZE_BY_CHAIN` obj in `consts.ts` too. I just thought the nested ternary expression was getting messy

2022-12-24 02:35 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +        const vaaKey = makeVaaKey(version, this.chain, emitter, data.sequence);
:+1:

2022-12-24 02:45 UTC, evan-gray requested changes
This is definitely coming together. Would you please add a test for all of the `getLastBlockByChain` cases and the Aptos watcher?

2022-12-24 02:45 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +      return chain === 'aptos' ? tokens.at(-1) : tokens[0];
Excited to get rid of this.

2022-12-24 02:45 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +    let fromBlock: number | null = lastReadBlock !== null ? Number(lastReadBlock) : toBlock;
The `Number` is now unnecessary, though (see other comment) I think the null check should remain because this should be able to start at the latest block if the last block isn't defined - useful for testing.

2022-12-24 02:45 UTC, evan-gray commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
I'm not sure this rewrite works the same way as the original logic. See the other comment where this is used. Can you retain the `null` functionality when these two doesn't exist and add a test?

2022-12-24 03:11 UTC, evan-gray commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
Added tests to confirm this will return `NaN` if the initial block is undefined.

2022-12-24 03:22 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +    let fromBlock: number | null = lastReadBlock !== null ? Number(lastReadBlock) : toBlock;
Fixed

2022-12-24 03:22 UTC, evan-gray commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
Fixed.

2022-12-24 05:15 UTC, evan-gray commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
They do not that I am aware of, at least not in the EVM watcher. It strictly adds every block, in the range, in order, to the object. Can you point out where this isn’t the case?

2022-12-24 06:54 UTC, heyitaki commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
Here, in the Aptos watcher! 😄 https://github.com/wormhole-foundation/wormhole-monitor/blob/2efdca2b52bc824fdfdf84fbe36408a8e98bac23/watcher/src/watchers/AptosWatcher.ts#L47

2022-12-24 07:03 UTC, heyitaki commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
Hmm @evan-gray, I don't see how `lastBlock` can ever be `undefined`. If it's not found in the db, it's assigned a fallback value from `INITIAL_DEPLOYMENT_BLOCK_BY_CHAIN`, which should always exist.

2022-12-24 07:04 UTC, heyitaki commented on watcher/src/databases/BigtableDatabase.ts
> +      return chain === 'aptos' ? tokens.at(-1) : tokens[0];
🤩

2022-12-24 12:36 UTC, evan-gray commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
It doesn’t always exist though (see the test) if I were to make a new watcher, say to add Solana, and didn’t put the initial value in yet, then the previous code would  `NaN`. There’s no requirement that initial deployment is populated for every chain.

2022-12-24 12:42 UTC, evan-gray commented on watcher/src/databases/JsonDatabase.ts
>        this.lastBlockByChain[chainId] = blockInfos[blockInfos.length - 1];
Okay, well now that I’m reading that code closer I have comments anyway. I do want to change what gets passed to the db side since the blocks are sparse now. In the meantime this code can be simplified if it’s not storing the last block in last block anyway (something we still likely want to remedy).

2022-12-24 13:06 UTC, evan-gray requested changes

2022-12-24 13:06 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +        const p2 = this.client.getTransactionByVersion(Number(version)).then((transaction) => {
Could we get better names than p1 and p2?

2022-12-24 13:06 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +      events.map(async ({ data, sequence_number, version }) => {
There’s only at most 25 events (could that cause a problem?). So I’m not sure we need to spam the RPC with 50 requests by awaiting all these at once. As you pointed out this also loses ordering. Is it worthwhile / clearer to
1. Separate awaiting all the blocks from awaiting all the transactions. 
2. Consider making it a requirement that this method return its object with the keys in order?
3. Alternatively, I was also considering making the return of this method less bad along with what we pass to the database. 

Too bad there doesn’t appear to be a way to make batch requests.

2022-12-24 13:50 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +        const p1 = this.client.getBlockByVersion(Number(version)).then((block) => {
You're right, code will be more readable if we hoist async calls to top of fn

2022-12-24 13:54 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +        const p2 = this.client.getTransactionByVersion(Number(version)).then((transaction) => {
Done

2022-12-24 14:37 UTC, heyitaki commented on watcher/src/watchers/AptosWatcher.ts
> +      events.map(async ({ data, sequence_number, version }) => {
Why would max 25 cause a problem? Imo, rather than enforcing synchronicity, it would be nice to ensure everything in the watcher can be run async and then enforce ordering in the db

2022-12-24 14:40 UTC, heyitaki commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
Ah I assumed `INITIAL_DEPLOYMENT_BLOCK_BY_CHAIN` would always be populated (and I still feel as though it should be). Maybe we can set all unimplemented chains to 0? Currently, if we set `lastBlock` to `null`, `watch` will loop forever without setting it

2022-12-24 14:53 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +      events.map(async ({ data, sequence_number, version }) => {
After discussion, I agree we have a solid path forward with changing the watcher to return an array of messages and concur with enforcing ordering in the db.

2022-12-24 14:59 UTC, evan-gray commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
Okay, this was a bug that you made me realize I introduced in 9ba5d02c30daa025fa6e814c45a74d915e00f4a6. Fixing now.

2022-12-24 15:13 UTC, evan-gray commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
Fixed. 🙂 This is significantly easier for testing (where the watcher can support starting from the current block), so I'd push for not requiring INITIAL_DEPLOYMENT_BLOCK_BY_CHAIN to be populated.

2022-12-24 15:37 UTC, heyitaki commented on watcher/src/databases/utils.ts
> +export const getLastBlockByChain = async (chain: ChainName): Promise<number> => {
I did like that the implementation was simpler with a fallback value of 0 but it makes sense to me that we can make the assumption that we are testing (and it would be more useful to start at latest block as a result) if both of those values are unset.

2022-12-24 16:25 UTC, evan-gray approved these changes
Rebased to perfection 🤝

2022-12-24 16:27 UTC, merged