WIP: added cloud functions module
wormhole-foundation/wormhole-monitor pull request #31
Opened 2022-12-27 20:52 UTC by ckeun

2022-12-29 04:52 UTC, ckeun commented
With the getRows ranges implementation: 
initial load time for getMessageCounts is 19 sec and each cache refresh is 600 ms
initial load time for getMessages is 4 sec (for Eth) and each cache refresh is 800 ms. however, cache refresh for hasSignedVaa=0 takes longer b/c you have to go back more blocks to find enough messages to return 😬

2022-12-29 18:54 UTC, ckeun commented
In getMessageCounts, realized that the numMessagesWithoutVaas metric wasn't updating correctly. Needed to do a fresh pull of rows to get updated data. Now storing the firstMissingVaaRowKey to have a starting point for those row ranges. 
The process now does two getRows() calls: (1) gets new messages, (2) gets missing vaas). This increases the overall time, but once we backfill the older missing vaas, the overall pull time should be ~1-1.5 sec.

2023-01-04 16:51 UTC, ckeun commented on cloud_functions/scripts/deploy.sh
> +gcloud functions deploy messages-test  --entry-point getMessages  --runtime nodejs16 --trigger-http --allow-unauthenticated --timeout 300 --memory 1GB
add flag for region "--region". deploy in same region as wormhole-mainnet "europe-west-3"

2023-01-04 17:44 UTC, evan-gray requested changes
Looking at these queries, feels like we want to index by the inverse block

2023-01-04 17:44 UTC, evan-gray commented on cloud_functions/src/getMessageCounts.ts
> +    const startRowKey = prevData.lastRowKey || padUint16(Number(prevChain).toString());
We'll need a way to reset these for when we fill gaps. Is it possible to add a flag like `forceRefresh` or something that we plan to call manually?

2023-01-04 17:44 UTC, evan-gray commented on cloud_functions/src/getMessageCounts.ts
> +    messages = await getMessageCounts_(cache['messages']);
I think you can simply try catch here and in the catch do a console.error, res.sendStatus(500), and return

2023-01-04 17:44 UTC, evan-gray commented on cloud_functions/src/getMessageCounts.ts
> +  try {
probably can avoid the try catch here in lieu of doing it outside so you can return a 500

2023-01-04 17:44 UTC, evan-gray commented on cloud_functions/src/getMessages.ts
> +          chain: parseInt(message?.id.split('/')[0]),
might want to perform this with 1 split like
```
const [chain, block, emitter, seq] = parseInt(message?.id.split('/')
```
and probably wrap this in an `if (message)` so you don't have to `?` everywhere

2023-01-04 17:44 UTC, evan-gray commented on cloud_functions/src/getMessages.ts
> +    // TODO: make noVaasBool a query param?
I approve of this TODO

2023-01-04 17:44 UTC, evan-gray commented on cloud_functions/src/getMessages.ts
> +let noVaaCache: MessagesByChain = {
change this to a function that returns the empty object. then call it once per cache

2023-01-05 19:46 UTC, evan-gray requested changes

2023-01-05 19:46 UTC, evan-gray commented on cloud_functions/src/getMessages.ts
> +      limit: numMessages,
if `fromKey` was passed in, can we do `numMessages+1` and then not return the first one?

2023-01-05 21:33 UTC, evan-gray approved these changes

2023-01-05 21:33 UTC, evan-gray commented
Great first iteration.

2023-01-05 21:38 UTC, merged