Near watcher
wormhole-foundation/wormhole-monitor pull request #34
Opened 2022-12-29 06:15 UTC by heyitaki

This PR adds a watcher for Near. A complication is that any data older than 5 epochs (~2.5 days) must hit an archival node to get data (https://docs.near.org/api/rpc/setup#querying-historical-data), but the NEAR-hosted archival node has rate limits of 600reqs/min per IP. Given that we're ~8936904 blocks behind current and this watcher makes 3 requests per block, we're looking at a 745hr backfill duration.

One possible solution may be to make use of NEAR Lake (https://docs.near.org/tools/realtime#near-lake-indexer) which aggregates event logs in an S3 bucket to backfill and NEAR's event WebSocket API to listen in real-time (https://docs.near.org/tools/realtime#listening-to-events-mainnet).

2022-12-29 13:02 UTC, evan-gray commented
For backfilling, I think it would be far easier to grab the transactions from https://explorer.near.org/accounts/contract.wormhole_crypto.near and backfill them in a one of script.

2022-12-29 14:07 UTC, heyitaki commented
Ok, I think that's a great idea, happy to proceed with that approach

2022-12-29 14:48 UTC, jumpsiegel approved these changes

2022-12-30 23:12 UTC, evan-gray requested changes
Mostly questions 🙃

2022-12-30 23:12 UTC, evan-gray commented on watcher/package.json
> +    "axios": "^1.1.3",
Why was this downgraded?

2022-12-30 23:12 UTC, evan-gray commented on watcher/src/consts.ts
> +export const NEAR_CONTRACT = 'contract.wormhole_crypto.near';
Whoever uses this should just use the SDK.

2022-12-30 23:12 UTC, evan-gray commented on watcher/src/types/near.ts
> +  version?: string; // this is supposed to exist but is missing in WH logs
@jumpsiegel thoughts? 🤔

2022-12-30 23:12 UTC, evan-gray commented on watcher/src/types/near.ts
> +export const isWormholePublishEventLog = (log: EventLog): log is WormholePublishEventLog => {
Function in a types file? Should these go in utils/near.ts (or something) instead?

2022-12-30 23:12 UTC, evan-gray commented on watcher/scripts/backfillNear.ts
> +  await storeVaasByBlock(watcher.chain, vaasByBlock);
How will this call work if the initDb hasn't been called? Did you mean to manually initialize a db and call storeVaasByBlock on it like the other scripts?

2022-12-30 23:12 UTC, evan-gray commented on watcher/scripts/backfillNear.ts
> +const backfillNear = async (fromBlock: number, toBlock: number): Promise<void> => {
Where / how does this get called?

2022-12-30 23:12 UTC, evan-gray commented on watcher/src/watchers/NearWatcher.ts
> +  async getProvider(): Promise<Provider> {
Why doesn't the constructor just do this?

2022-12-30 23:14 UTC, heyitaki commented on watcher/package.json
> +    "axios": "^1.1.3",
from the description in that commit message: "fixes issue described here: https://github.com/axios/axios/issues/5346"

2022-12-30 23:16 UTC, heyitaki commented on watcher/src/types/near.ts
> +export const isWormholePublishEventLog = (log: EventLog): log is WormholePublishEventLog => {
this is a type guard, so i thought it could go here, but i don't have a strong opinion where we put it... i'll move it to utils

2022-12-30 23:17 UTC, heyitaki commented on watcher/src/watchers/NearWatcher.ts
> +  async getProvider(): Promise<Provider> {
this is an async method, constructors are by definition not async because they return the object they are constructing whereas async methods return a promise

2022-12-31 09:18 UTC, heyitaki commented on watcher/scripts/backfillNear.ts
> +const backfillNear = async (fromBlock: number, toBlock: number): Promise<void> => {
resolved, changed to an IIFE like the other scripts

2022-12-31 09:18 UTC, heyitaki commented on watcher/scripts/backfillNear.ts
> +  await storeVaasByBlock(watcher.chain, vaasByBlock);
Good catch, fixed

2022-12-31 09:19 UTC, heyitaki commented on watcher/src/consts.ts
> +export const NEAR_CONTRACT = 'contract.wormhole_crypto.near';
Fixed

2022-12-31 13:51 UTC, evan-gray commented on watcher/package.json
> +    "axios": "^1.1.3",
But we already had code to avoid this without downgrading
https://github.com/wormhole-foundation/wormhole-monitor/blob/main/watcher/src/watchers/EVMWatcher.ts#L16
Did this not work?

2022-12-31 13:53 UTC, evan-gray commented on watcher/src/watchers/NearWatcher.ts
> +  async getProvider(): Promise<Provider> {
Fair. Clearly I had a case of the Fridays when reviewing 😁 Wonder why connect is async. Must do some call 🤷‍♂️

2022-12-31 13:56 UTC, evan-gray commented on watcher/src/types/near.ts
> +export const isWormholePublishEventLog = (log: EventLog): log is WormholePublishEventLog => {
I agree that I don’t care that much where these go either 🙂

2023-01-01 23:28 UTC, heyitaki commented on watcher/src/types/near.ts
> +export const isWormholePublishEventLog = (log: EventLog): log is WormholePublishEventLog => {
moved to `utils/types.ts`!

2023-01-01 23:53 UTC, heyitaki commented on watcher/package.json
> +    "axios": "^1.1.3",
Ahh nice, fixed using that header

2023-01-01 23:58 UTC, heyitaki commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
> +    expect(blockKeys[0]).toEqual('74616314/1663786085392436500');
The block number used in `blockKey` can be different than the block number in the emitted WH log because a transaction can have execution outcomes that resolve and finalize in future blocks. This *should* be fine, but just want to get thoughts here @jumpsiegel @evan-gray

2023-01-02 14:36 UTC, jumpsiegel commented on watcher/src/types/near.ts
> +  version?: string; // this is supposed to exist but is missing in WH logs
There is iron in his words...  there is no version in the emitted event.  https://github.com/wormhole-foundation/wormhole/blob/98c843e85d19756b43df407e1fd85363d1a1b4c4/near/contracts/wormhole/src/lib.rs#L56

Probably worth adding it but unclear if it is worth actually upgrading the contract...

2023-01-02 15:04 UTC, jumpsiegel approved these changes

2023-01-02 15:08 UTC, jumpsiegel commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
> +    expect(blockKeys[0]).toEqual('74616314/1663786085392436500');
Another snowflake.. like sui and aptos and their sequence numbers.  We are still using the block number of the transaction itself

2023-01-02 15:10 UTC, jumpsiegel commented on watcher/src/watchers/NearWatcher.ts
> +        for (const log of logs) {
The "standard" is lower here then in the actual watcher in the guardian.  We are limiting ourselves to transactions that are finalized but exposing ourselves to the case where the WH message itself might be in a non-finalized outcome in a finalized transaction.    I think this is ok since this is just the monitor and we might only get a false positive or negative as a result (never seen in production during my tests).

2023-01-02 19:54 UTC, heyitaki commented on watcher/src/watchers/NearWatcher.ts
> +        for (const log of logs) {
Agreed - I'm tracking that in issue https://github.com/wormhole-foundation/wormhole-monitor/issues/36, but have held off on addressing it for now because 1) it's extremely low probability and 2) might require a solution that complicates the code quite a bit (introduction of a poll-based queue system)

2023-01-03 17:35 UTC, evan-gray commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
> +    expect(blockKeys[0]).toEqual('74616314/1663786085392436500');
I agree this feels correct to use the block of the tx and not the log

2023-01-03 17:39 UTC, evan-gray approved these changes

2023-01-03 17:43 UTC, evan-gray requested changes
attempting to run the backfill resulted in a 429 and crash ☹️

2023-01-03 18:40 UTC, ckeun commented on watcher/scripts/backfillNear.ts
> +  blockHashes.forEach(async (hash) => {
i think there's sometimes an issue when using async/await inside a forEach? but if you're getting the correct result in the blocks array, then probs can ignore this comment

2023-01-03 20:47 UTC, heyitaki commented on watcher/scripts/backfillNear.ts
> +  blockHashes.forEach(async (hash) => {
Yes that was the issue, forEach discards the promises instead of awaiting them... fixed now :)

2023-01-05 16:44 UTC, evan-gray approved these changes

2023-01-05 16:45 UTC, merged