watcher/src - cosmwasm watcher
wormhole-foundation/wormhole-monitor pull request #41
Opened 2023-01-04 19:23 UTC by panoel

2023-01-04 19:36 UTC, heyitaki requested changes

2023-01-04 19:36 UTC, heyitaki commented on watcher/src/watchers/CosmwasmWatcher.ts
> +      var blockHeight = result.block.header.height;
Nit: can we replace uses of `var` with `let`/`const`?

2023-01-04 19:55 UTC, panoel commented on watcher/src/watchers/CosmwasmWatcher.ts
> +      var blockHeight = result.block.header.height;
Oops.  Fixed.

2023-01-04 20:00 UTC, panoel commented on watcher/src/watchers/CosmwasmWatcher.ts
> +          if (hashResult && hashResult.tx_response.events) {
Added more types.

2023-01-05 15:05 UTC, panoel commented on watcher/src/watchers/CosmwasmWatcher.ts
> +          if (hashResult && hashResult.tx_response.events) {
Added.

2023-01-05 16:27 UTC, heyitaki approved these changes

2023-01-05 18:36 UTC, merged