near: add all blocks to vaasByBlock
wormhole-foundation/wormhole-monitor pull request #47
Opened 2023-01-05 21:15 UTC by heyitaki

2023-01-05 21:31 UTC, evan-gray approved these changes

2023-01-05 21:31 UTC, evan-gray requested changes
Fix the tests pls 🙂

2023-01-06 14:39 UTC, evan-gray requested changes

2023-01-06 14:39 UTC, evan-gray commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
>    expect(Object.keys(messages).length).toEqual(0);
Shouldn't this equal 1 since getMessagesForBlocks should be inclusive on both ends?

2023-01-06 14:39 UTC, evan-gray commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
> +    console.log(JSON.stringify(messages, null, 2));
Let's keep the tests clean and remove the console.log 🙂

2023-01-06 15:03 UTC, heyitaki commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
> +    console.log(JSON.stringify(messages, null, 2));
Good catch, fixed

2023-01-06 15:26 UTC, evan-gray commented on watcher/src/watchers/__tests__/NearWatcher.test.ts
>    expect(Object.keys(messages).length).toEqual(0);
ah, rtf-comment 🤦

2023-01-06 15:30 UTC, evan-gray approved these changes

2023-01-06 15:35 UTC, evan-gray approved these changes

2023-01-06 15:36 UTC, merged