Solana watcher
wormhole-foundation/wormhole-monitor pull request #55
Opened 2023-01-11 06:40 UTC by heyitaki

This PR adds a watcher for Solana. It uses the [`getSignaturesForAddress`](https://docs.solana.com/developing/clients/jsonrpc-api#getsignaturesforaddress) API to grab transactions that list the Wormhole core bridge contract under `accountKeys` and parses the associated instructions to retrieve the payload from the corresponding message account.

Highly recommended to use a faster RPC node than the default, even to run tests.

2023-01-12 03:37 UTC, ckeun commented on watcher/src/watchers/SolanaWatcher.ts
> +      fromBlock = await this.connection.getBlock(fromSlot, { maxSupportedTransactionVersion: 0 });
is there a risk of double evaluating blocks? e.g., start at (fromBlock=10, toBlock=11) <-- it looks like it's iterating through all of the transactions in both of these blocks... then does it go (fromBlock=11, toBlock=12) and re-evaluate the transactions in Block 11?

2023-01-12 03:48 UTC, heyitaki commented on watcher/src/watchers/SolanaWatcher.ts
> +      fromBlock = await this.connection.getBlock(fromSlot, { maxSupportedTransactionVersion: 0 });
Within a single call of this method we should walk through every transaction once. You're right that this method is inclusive of `fromBlock` and `toBlock`, but the way `watch` works in `Watcher.ts`, `fromBlock` is incremented to one above `toBlock`, so we need to traverse all transactions in `fromBlock` in all cases but the first iteration when we fetch the last block from the db. We can (and should?) eliminate that case, by changing `fromBlock` to be the block after the last recorded block in the db.

2023-01-12 04:58 UTC, ckeun commented on watcher/src/watchers/SolanaWatcher.ts
> +      fromBlock = await this.connection.getBlock(fromSlot, { maxSupportedTransactionVersion: 0 });
ah okay, so you're going 2x2.  👍

2023-01-12 05:01 UTC, ckeun commented on watcher/src/watchers/SolanaWatcher.ts
> +      toSlot.toString(),
should the lastBlockKey be using fromSlot.toString()? in case it crashes, it'll make sure to re-evaluate the fromSlot() again?

2023-01-12 16:58 UTC, evan-gray commented on watcher/src/watchers/SolanaWatcher.ts
> +    return Object.assign({ [lastBlockKey]: [] }, vaasByBlock);
Let's just return `{ [lastBlockKey]: [], ...vaasByBlock}`?

2023-01-12 17:17 UTC, heyitaki commented on watcher/src/watchers/SolanaWatcher.ts
> +    return Object.assign({ [lastBlockKey]: [] }, vaasByBlock);
We should either reverse keys before returning (since they are currently returned in reverse chronological order) or search `vaasByBlock` for the last block in `storeVaasByBlock`. After discussion, the second approach is preferred because it is more modular.

2023-01-12 17:17 UTC, heyitaki commented on watcher/src/watchers/__tests__/SolanaWatcher.test.ts
> +import dotenv from 'dotenv';
Would be nice to add a test to ensure that repeated calls of `getMessagesForBlocks` on adjacent block ranges don't duplicate (or drop) messages

2023-01-12 17:17 UTC, heyitaki commented on watcher/src/watchers/__tests__/SolanaWatcher.test.ts
> +import dotenv from 'dotenv';
Also a test to validate `blockKey` and `vaaKey` (to ensure things like human readable timestamp instead of unix timestamp 😛)

2023-01-15 15:49 UTC, heyitaki commented on watcher/src/watchers/SolanaWatcher.ts
> +    return Object.assign({ [lastBlockKey]: [] }, vaasByBlock);
Fixed

2023-01-15 15:49 UTC, heyitaki commented on watcher/src/watchers/SolanaWatcher.ts
> +    return Object.assign({ [lastBlockKey]: [] }, vaasByBlock);
Fixed

2023-01-15 15:49 UTC, heyitaki commented on watcher/src/watchers/__tests__/SolanaWatcher.test.ts
> +import dotenv from 'dotenv';
Both added

2023-01-18 04:37 UTC, ckeun approved these changes

2023-01-18 18:19 UTC, evan-gray commented on watcher/src/utils/aptos.ts
> +export const isValidBlockKey = (key: string) => {
I think these could be implemented as static methods on the corresponding classes, that way the aptos one can override the default one (which seems like what you're going for).

2023-01-18 18:22 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +    let fromBlock: number | null = lastBlock ? lastBlock + 1 : null;
This makes me feel better, but also sad to have messed it up.

2023-01-18 18:25 UTC, evan-gray commented on watcher/src/watchers/SolanaWatcher.ts
> +    this.maximumBatchSize = 100000;
@panoel would like underscores for "older-eyes"

2023-01-18 18:37 UTC, evan-gray commented on watcher/src/watchers/SolanaWatcher.ts
> +        const res = await this.connection.getTransaction(signature, {
Can you add a comment at the top of this block that explains the process here.

2023-01-18 18:42 UTC, evan-gray commented on watcher/src/watchers/SolanaWatcher.ts
> +      currSignature = signatures.at(-1)?.signature;
Can we double check that this should be the last one?

2023-01-18 18:44 UTC, evan-gray commented on watcher/src/watchers/__tests__/SolanaWatcher.test.ts
> +jest.setTimeout(6000000);
umm...

2023-01-20 15:56 UTC, heyitaki commented on watcher/src/databases/BigtableDatabase.ts
> +      const blockInfos = Object.keys(vaasByBlock).sort();
Fixed, we now parse the block number and use that to compare

2023-01-20 15:57 UTC, heyitaki commented on watcher/src/databases/JsonDatabase.ts
> +    const blockInfos = Object.keys(vaasByBlock).sort();
Fixed

2023-01-20 15:57 UTC, heyitaki commented on watcher/src/types/aptos.ts
> +export type AptosEvent = Omit<Types.Event, 'data'> & {
Where did you come from cotton eye joe

2023-01-20 15:58 UTC, heyitaki commented on watcher/src/utils/aptos.ts
> +export const isValidBlockKey = (key: string) => {
Moved to watchers, although decided not to make them static as the base `isValidBlockKey` uses the `chain` field. Can make watcher pass in chain as a param and make these methods static if you have a strong opinion

2023-01-20 15:59 UTC, heyitaki commented on watcher/src/watchers/SolanaWatcher.ts
> +    this.maximumBatchSize = 100000;
Fixed

2023-01-20 15:59 UTC, heyitaki commented on watcher/src/watchers/SolanaWatcher.ts
> +  getSignaturesLimit = GET_SIGNATURES_LIMIT; // modifiable in tests
Added

2023-01-20 16:01 UTC, heyitaki commented on watcher/src/watchers/__tests__/SolanaWatcher.test.ts
> +jest.setTimeout(6000000);
Fixed 😅

2023-01-21 01:04 UTC, evan-gray requested changes

2023-01-21 01:04 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +    let fromBlock: number | null = lastBlock ? lastBlock + 1 : null;
Wait a minute... this is now wrong on the initial block.

2023-01-21 01:07 UTC, heyitaki commented
@egray you're right it should be 
```
let fromBlock: number = lastBlock ? lastBlock + 1 : INITIAL_DEPLOYMENT_BLOCK_BY_CHAIN.solana;
```

2023-01-21 01:08 UTC, heyitaki commented on common/src/consts.ts
> +  solana: '96383501',
Hm I wrote a script to fetch it, perhaps it was only looking for txs with `postMessage` instructions...

2023-01-21 01:33 UTC, evan-gray requested changes

2023-01-21 01:33 UTC, evan-gray commented on watcher/src/watchers/SolanaWatcher.ts
> +    const toBlock = await this.connection.getBlock(toSlot, { maxSupportedTransactionVersion: 0 });
Not having this in a try/catch like the `fromBlock` results in an error on backfilling when it naturally lands on a skipped `toBlock`

2023-01-21 01:34 UTC, evan-gray commented
Fixed all outstanding issues.

2023-01-21 01:53 UTC, evan-gray approved these changes

2023-01-21 01:56 UTC, merged