scripts: improve locateMessageGaps
wormhole-foundation/wormhole-monitor pull request #59
Opened 2023-01-13 03:36 UTC by evan-gray

2023-01-13 06:17 UTC, heyitaki requested changes

2023-01-13 06:17 UTC, heyitaki commented on watcher/scripts/locateMessageGaps.ts
> +      const endBlock = parseInt(range[1]);
Nit: rename to `endOfRange` to match naming of `startOfRange`, or even better, `rangeStart` and `rangeEnd`

2023-01-13 06:17 UTC, heyitaki commented on watcher/scripts/locateMessageGaps.ts
> +      if (prevChain === chain && startOfRange < fromBlock) {
Should we store last block by `` `${chain}/${emitter}` `` here? Or sort `gaps` by chainId, then emitter, then sequence number? Right now this check isn't very efficient since gaps is not guaranteed to be ordered by chain

2023-01-13 06:17 UTC, heyitaki commented on watcher/scripts/locateMessageGaps.ts
> +        fromBlock = toBlock + 1;
Let's wrap these two lines with `if (!found) { ...` instead of the inverse

2023-01-14 00:13 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +        fromBlock = toBlock + 1;
:+1:

2023-01-14 00:58 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +      if (prevChain === chain && startOfRange < fromBlock) {
Good catch

2023-01-14 01:03 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
>        }
Fixed

2023-01-14 01:03 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +      let watcher = new Watcher(chainName);
Fixed

2023-01-14 01:04 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +      const endBlock = parseInt(range[1]);
Fixed

2023-01-14 01:04 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +        fromBlock = toBlock + 1;
Fixed

2023-01-14 05:35 UTC, heyitaki approved these changes

2023-01-14 05:35 UTC, heyitaki commented on watcher/scripts/locateMessageGaps.ts
> +            bt.storeVaasByBlock(chainName, { [message[0]]: locatedMessages }, false);
Two questions:
1. Would it make more sense to filter `messages` and store the bulk result to db instead of calling `storeVaasByBlock` once per block?
2. Is this meant to not be awaited to speed up the loop?

2023-01-14 05:35 UTC, heyitaki commented on watcher/scripts/locateMessageGaps.ts
> +      const [aChain, , aEmitter, aSequence] = a.split('/');
Nit: here and on L107, can you use underscores for unused array destructured elems? Makes it more legible

2023-01-15 15:41 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +            bt.storeVaasByBlock(chainName, { [message[0]]: locatedMessages }, false);
1. Let's take this as a future optimization. It's unlikely that we'll find two of the messages we're looking for in the same batch and we'd have to rewrite the style of looping over `gaps` to be able to know we hit them. This current code, `locatedMessages` should only ever be length 1 or 0.
2. Heh, no, nice catch.

2023-01-15 15:44 UTC, evan-gray commented on watcher/scripts/locateMessageGaps.ts
> +      const [aChain, , aEmitter, aSequence] = a.split('/');
Fixed

2023-01-15 16:01 UTC, heyitaki commented on watcher/scripts/locateMessageGaps.ts
> +            bt.storeVaasByBlock(chainName, { [message[0]]: locatedMessages }, false);
Ok let's leave it for the future. I was thinking it would speed up cases in which we have several consecutive missing messages but we can revisit if we come across such a case

2023-01-15 16:02 UTC, heyitaki approved these changes

2023-01-15 16:02 UTC, merged