Arbitrum watcher
wormhole-foundation/wormhole-monitor pull request #61
Opened 2023-01-13 04:54 UTC by panoel

This is a draft PR.  Please look to see if anything is awry while I write tests.
I'll remove the `lastEthTime` variable from ArbitrumWatcher.ts when testing is complete.

2023-01-17 14:33 UTC, evan-gray reviewed
Excited for tests 🙂

2023-01-17 14:33 UTC, evan-gray commented on watcher/src/watchers/EVMWatcher.ts
> +      this.maximumBatchSize = 10;
Could you move this to an override in the Arbitrum class, since it has its own?

2023-01-17 14:33 UTC, evan-gray commented on watcher/src/watchers/ArbitrumWatcher.ts
> +
See below comment, I think you can do `maximumBatchSize = 10` here. Nicer to keep the arbitrum related code all together.

2023-01-17 16:39 UTC, panoel commented on watcher/src/watchers/EVMWatcher.ts
> +      this.maximumBatchSize = 10;
Fixed

2023-01-17 16:39 UTC, panoel commented on watcher/src/watchers/ArbitrumWatcher.ts
> +
Done

2023-01-18 04:38 UTC, ckeun submitted a review, later dismissed

2023-01-18 19:20 UTC, evan-gray requested changes

2023-01-18 19:20 UTC, evan-gray commented on watcher/src/watchers/ArbitrumWatcher.ts
> +    if (now - this.lastEthTime < 300_000) {
Good to change this to 30s?

2023-01-18 19:20 UTC, evan-gray commented on watcher/src/watchers/ArbitrumWatcher.ts
> +      await axios.post(
Can we add a type to this post call with at least limited set of fields you're using 🙂

2023-01-18 19:32 UTC, heyitaki commented on watcher/src/watchers/ArbitrumWatcher.ts
> +            params: [l2BlockNumber, false],
@panoel as discussed, it would be nice to replace this call with the [arbitrum SDK](https://www.npmjs.com/package/@arbitrum/sdk). This endpoint in `ArbitrumProvider` might help: https://github.com/OffchainLabs/arbitrum-sdk/blob/main/src/lib/utils/arbProvider.ts#L101

2023-01-19 02:21 UTC, merged