scripts: dumpVAAs and simplify updateRows
wormhole-foundation/wormhole-monitor pull request #63
Opened 2023-01-19 01:24 UTC by evan-gray

2023-01-19 03:07 UTC, ckeun commented on watcher/scripts/dumpVAAs.ts
> +            end: `${chain}:z`,
what does the `z` char do here? 🤔 🪄

2023-01-19 12:56 UTC, evan-gray commented on watcher/scripts/dumpVAAs.ts
> +            end: `${chain}:z`,
I was hoping it would be the last possible character (exclusive) of an emitter since I couldn’t just add 1 to the chain id since 10 comes before 9 😢 open to ideas

2023-01-19 13:57 UTC, panoel commented on watcher/scripts/dumpVAAs.ts
> +      let log = ora(`Fetching all ${chainName} VAAs...`).start();
Wow!  Fancy!

2023-01-19 14:05 UTC, panoel commented on watcher/scripts/dumpVAAs.ts
> +const LIMIT = 10000;
Just out of curiosity, why do 10_000 at a time?  A limit somewhere or just a good round number?

2023-01-19 14:30 UTC, panoel submitted a review, later dismissed

2023-01-19 15:13 UTC, ckeun commented on watcher/scripts/dumpVAAs.ts
> +            end: `${chain}:z`,
ahhh 👌 loll my implementation was much more hobo. this looks great. 🤣 👏

2023-01-19 15:17 UTC, ckeun commented on watcher/scripts/updateRows.ts
> +    '00015/18446744073636435649/148410499d3fcda4dcfd68a1ebfcdddda16ab28326448d4aae4d2f0465cdfcb7/00000000000000000001',
a bespoke script 🧐

2023-01-19 15:17 UTC, ckeun submitted a review, later dismissed

2023-01-19 15:51 UTC, heyitaki requested changes

2023-01-19 15:51 UTC, heyitaki commented on watcher/scripts/dumpVAAs.ts
> +      let log = ora(`Fetching all ${chainName} VAAs...`).start();
Looks like this could be a const :)

2023-01-19 15:51 UTC, heyitaki commented on watcher/scripts/dumpVAAs.ts
> +        vaaRows = vaaRows.filter((row) => row.id.toString() !== start.toString());
Is this to make it exclusive so `start` isn't double counted between loops? Just want to make sure that it's returning vaas in reverse chronological  order 

Also we shouldn't have to filter since we know that start is the last index or none

2023-01-19 15:51 UTC, heyitaki commented on watcher/scripts/dumpVAAs.ts
> +        start = vaaRows.length === LIMIT ? vaaRows[LIMIT - 1].id : '';
I like how we're standardizing this logic 😄

2023-01-19 15:51 UTC, heyitaki commented on watcher/scripts/updateRows.ts
> +// The `2` signifies this is a known miss which has been accounted for
When would we leave it as a known miss instead of filling it?

It would be awesome to turn this param of `updateMessageStatuses` to an enum and add some comments explaining each entry

2023-01-19 19:58 UTC, evan-gray commented on watcher/scripts/dumpVAAs.ts
> +const LIMIT = 10000;
I was getting hangs when making too big of a request to bigtable. 😕

2023-01-19 19:59 UTC, evan-gray commented on watcher/scripts/updateRows.ts
> +    '00015/18446744073636435649/148410499d3fcda4dcfd68a1ebfcdddda16ab28326448d4aae4d2f0465cdfcb7/00000000000000000001',
Yes, for now (since we rarely expect to do this) you would just update that constant when you need to set something to "2".

2023-01-21 01:39 UTC, evan-gray commented on watcher/scripts/dumpVAAs.ts
> +const LIMIT = 10000;
Good reminder to leave a comment though!

2023-03-15 14:31 UTC, evan-gray commented
https://github.com/wormhole-foundation/wormhole-dashboard/pull/60

2023-03-15 14:31 UTC, closed without merging