watcher: add Optimism
wormhole-foundation/wormhole-monitor pull request #67
Opened 2023-01-19 20:23 UTC by panoel

This is a draft PR.  I put the ABI.json file into the types folder.  Please let me know if that is acceptable.

2023-01-20 16:21 UTC, evan-gray requested changes
Great how simple it is! Just a couple cleanup things.

2023-01-20 16:21 UTC, evan-gray commented on watcher/src/watchers/OptimismWatcher.ts
> +    this.rpc = RPCS_BY_CHAIN[this.chain];
I don't think you need this anymore 🙂

2023-01-20 16:21 UTC, evan-gray commented on watcher/src/watchers/OptimismWatcher.ts
> +    if (!this.rpc) {
and therefore don't need these checks 🙌

2023-01-20 16:21 UTC, evan-gray commented on watcher/src/watchers/OptimismWatcher.ts
> +              'finalized', // does the guardian use latest?
we can remove this comment since I don't think the guardian works this way (yet?)

2023-01-20 16:21 UTC, evan-gray commented on watcher/src/watchers/__tests__/OptimismWatcher.test.ts
> +// The following test will be enabled when there is a block to see.
lol, I was super confused until I read this 😅

2023-01-20 16:45 UTC, panoel commented on watcher/src/watchers/OptimismWatcher.ts
> +    this.rpc = RPCS_BY_CHAIN[this.chain];
Removed

2023-01-20 16:45 UTC, panoel commented on watcher/src/watchers/OptimismWatcher.ts
> +    if (!this.rpc) {
Removed

2023-01-20 16:46 UTC, panoel commented on watcher/src/watchers/__tests__/OptimismWatcher.test.ts
> +// The following test will be enabled when there is a block to see.
Is there a way for us to put a block on Optimism mainnet so that we can add this test?

2023-01-20 16:49 UTC, panoel commented on watcher/src/watchers/OptimismWatcher.ts
> +              'finalized', // does the guardian use latest?
Removed

2023-01-20 23:58 UTC, evan-gray commented on watcher/src/watchers/__tests__/OptimismWatcher.test.ts
> +// The following test will be enabled when there is a block to see.
good point I made one for you 😉

2023-01-21 02:17 UTC, evan-gray requested changes

2023-01-21 02:17 UTC, evan-gray commented on watcher/src/watchers/OptimismWatcher.ts
> +    const gtbData = contract.encodeFunctionData('getTotalBatches');
Upon further review I think we're missing something. `getTotalBatches` is the batch which is posted to the l1 and contains blocks. Maybe `getTotalElements` is the right one?

2023-01-21 02:45 UTC, evan-gray commented
Made outstanding fixes

2023-01-21 02:45 UTC, evan-gray approved these changes

2023-01-21 02:53 UTC, merged