watcher/src/databases: addMissingVAAa
wormhole-foundation/wormhole-monitor pull request #77
Opened 2023-02-01 23:33 UTC by panoel

2023-02-02 02:26 UTC, evan-gray requested changes
just some small things, but excited to try this out!

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +    const filter = [
Guessing you copied this from a query, but it's not used here.

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +  columnFamilies: string[] = [
should we call this vaaColumnFamilies since there's two bigtables referenced in this file?

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +  makeRowKey(emitterChain: number, emitterAddress: string, sequence: number): string {
ooh, I think you can use `makeVaaId` from utils!

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +import { ParsedVaa, parseVaa, SignedVaa } from '@certusone/wormhole-sdk/lib/cjs/vaa/wormhole';
the `ParsedVaa` import is unused.

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +  async WriteVAAToDB(signedVAA: SignedVaa): Promise<void> {
Camel case this method name, I think, please.

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +    let marshalledVAA = { value: signedVAA, timestamp: ts.toString() };
I'm not 100% about the timestamp here, as in I'm not sure if the guardian is explicitly adding a timestamp of if it's being added automatically (I know they're not 0). One day someone will redo this vaa db.

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +    let marshalledVAA = { value: signedVAA, timestamp: ts.toString() };
More importantly, I'm not sure if this will work for the format of signedVAA. I _think_ it will just get converted to whatever binary format is appropriate, but maybe we just try it out once and see what happens.

2023-02-02 02:26 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +    this.logger.info(`wrote ${rowKey} => ${marshalledVAA}`);
the `marshalledVAA` value might be kinda big to write. maybe just rowKey is fine.

2023-02-02 13:48 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +    const filter = [
Fixed

2023-02-02 13:49 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +import { ParsedVaa, parseVaa, SignedVaa } from '@certusone/wormhole-sdk/lib/cjs/vaa/wormhole';
Fixed

2023-02-02 13:49 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +  async WriteVAAToDB(signedVAA: SignedVaa): Promise<void> {
Fixed

2023-02-02 13:50 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +    this.logger.info(`wrote ${rowKey} => ${marshalledVAA}`);
fixed

2023-02-02 13:55 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +  columnFamilies: string[] = [
Fixed.

2023-02-02 14:06 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +  makeRowKey(emitterChain: number, emitterAddress: string, sequence: number): string {
Fixed

2023-02-02 14:29 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +    let marshalledVAA = { value: signedVAA, timestamp: ts.toString() };
Would like to test it and see what happens.

2023-02-02 19:07 UTC, evan-gray requested changes

2023-02-02 19:07 UTC, evan-gray commented on watcher/src/databases/BigtableDatabase.ts
> +        this.writeVAAsToDB(foundRecords);
I think we want the inverse of this, right? These VAAs were already _in_ the bigtable, but we want the ones we _didn't_ find in the bigtable so we can go try to look them up and put them there.

2023-02-02 20:54 UTC, panoel commented on watcher/src/databases/BigtableDatabase.ts
> +        this.writeVAAsToDB(foundRecords);
Hopefully fixed.

2023-03-02 17:43 UTC, evan-gray approved these changes

2023-03-02 17:59 UTC, merged