Injective watcher: change to explorer rpc
wormhole-foundation/wormhole-monitor pull request #95
Opened 2023-02-22 15:41 UTC by panoel

This uses the Injective explorer/api endpoint

2023-02-23 20:44 UTC, evan-gray requested changes

2023-02-23 20:44 UTC, evan-gray commented on watcher/src/watchers/CosmwasmWatcher.ts
> +              let emitter = hashResult.data.messages[j].value.sender;
I think this sender is the wallet, but we want the emitter address

2023-02-23 20:44 UTC, evan-gray commented on watcher/src/watchers/CosmwasmWatcher.ts
> +              let sequence = hashResult.data.signatures[j].sequence;
I think this sequence is the wallet sequence, but we want the wormhole core log sequence number

2023-02-23 22:04 UTC, evan-gray commented
Confirmed the explorer endpoints do not have logs available at this time so this doesn't look feasible as there's no way to determine which transactions involve the core bridge.

2023-02-28 19:28 UTC, panoel commented on watcher/src/watchers/CosmwasmWatcher.ts
> +              let emitter = hashResult.data.messages[j].value.sender;
Fixed

2023-02-28 19:28 UTC, panoel commented on watcher/src/watchers/CosmwasmWatcher.ts
> +              let sequence = hashResult.data.signatures[j].sequence;
Fixed

2023-02-28 20:30 UTC, evan-gray requested changes
I think there's a faster way to do `getMessagesForBlocks_explorer`, if you simply call `api/explorer/v1/txs` and then paginate back until getting a transaction which the block is `< fromBlock`. Also wondering if this should just be moved to it's own class - might be cleaner :)

2023-03-01 17:04 UTC, panoel commented
Moved Injective to separate class.

2023-03-15 14:32 UTC, evan-gray commented
https://github.com/wormhole-foundation/wormhole-dashboard/pull/62

2023-03-15 14:32 UTC, closed without merging